#!/usr/bin/env bash
# Build BedrockOnLinux.app, the macOS application bundle.
# Usage: scripts/build-macos-app.sh   -> dist/BedrockOnLinux-<ver>-macos.zip
#
# Must run ON macOS: the Qt wheels it bundles are macOS binaries, and pip only
# resolves those on a Mac. It deliberately does not bundle a Windows runtime --
# Game Porting Toolkit and CrossOver are separate installs with their own
# licences, and bol.winemac finds whichever one the player has.
#
# Codesigning is left to the caller. An unsigned bundle runs after the usual
# right-click-Open (or `xattr -dr com.apple.quarantine`); to ship one, set
# CODESIGN_IDENTITY and it is signed with hardened runtime.
set -euo pipefail

SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VER="$(grep -m1 '^VERSION = ' "$SRC/bol/config.py" | cut -d'"' -f2)"
OUT="$SRC/dist"
APP="$OUT/BedrockOnLinux.app"
BUNDLE_ID="io.github.wyze3306.BedrockOnLinux"
PYTHON="${PYTHON:-python3}"

[[ "$(uname -s)" == "Darwin" ]] || {
  echo "This builds a macOS bundle and must run on macOS." >&2
  exit 1
}
[[ -f "$SRC/data/icon.png" ]] || { echo "data/icon.png missing" >&2; exit 1; }

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cp -r "$SRC/bol" "$APP/Contents/Resources/bol"
install -m755 "$SRC/bedrock-on-linux" "$APP/Contents/Resources/bedrock-on-linux"
cp "$SRC/data/icon.png" "$APP/Contents/Resources/icon.png"
find "$APP/Contents/Resources" -name __pycache__ -type d -exec rm -rf {} +

# The Qt toolkit, beside bol/ so it is on sys.path with nothing to install.
# python-xlib is deliberately absent: it talks to an X server, and bol.deps
# drops it from the macOS dependency set for the same reason.
"$PYTHON" -m pip install --quiet --no-cache-dir --no-compile --no-deps \
  --only-binary=:all: --target "$APP/Contents/Resources" \
  "PySide6-Essentials==6.9.3" "shiboken6==6.9.3" "packaging==26.2" \
  "cryptography==43.0.3"
rm -rf "$APP/Contents/Resources/bin"
find "$APP/Contents/Resources" -name __pycache__ -type d -exec rm -rf {} +

# The icon. iconutil wants a full .iconset; sips does the resizing.
ICONSET="$OUT/icon.iconset"
rm -rf "$ICONSET"
mkdir -p "$ICONSET"
for size in 16 32 64 128 256 512; do
  sips -z "$size" "$size" "$SRC/data/icon.png" \
    --out "$ICONSET/icon_${size}x${size}.png" >/dev/null
  double=$((size * 2))
  sips -z "$double" "$double" "$SRC/data/icon.png" \
    --out "$ICONSET/icon_${size}x${size}@2x.png" >/dev/null
done
iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/icon.icns"
rm -rf "$ICONSET"

# The bundle's executable. A shell stub rather than a compiled launcher: it
# keeps the bundle buildable with nothing but the system Python.
#
# It runs the repository's own entry script out of Resources, and that detail
# matters twice. The script finds bol/ beside itself, so nothing depends on
# PYTHONPATH; and it makes sys.argv[0] a path inside the bundle, which is how
# bol.update recognises that it is running from one -- an app updates by being
# replaced whole, not by having a single file inside it overwritten. A
# `python3 -c` invocation would leave argv[0] as "-c" and lose both.
#
# /usr/bin/python3 is macOS's own; the Qt and cryptography wheels bundled
# above are abi3, so any Python 3.9 or newer loads them. BOL_PYTHON overrides
# it for anyone testing against a Homebrew build.
cat > "$APP/Contents/MacOS/BedrockOnLinux" <<'LAUNCHER'
#!/bin/sh
# Generated by scripts/build-macos-app.sh — do not edit in the bundle.
here="$(cd "$(dirname "$0")" && pwd)"
resources="$(cd "$here/../Resources" && pwd)"
exec "${BOL_PYTHON:-/usr/bin/python3}" "$resources/bedrock-on-linux" "$@"
LAUNCHER
chmod 755 "$APP/Contents/MacOS/BedrockOnLinux"

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>BedrockOnLinux</string>
  <key>CFBundleDisplayName</key><string>BedrockOnLinux</string>
  <key>CFBundleIdentifier</key><string>${BUNDLE_ID}</string>
  <key>CFBundleVersion</key><string>${VER}</string>
  <key>CFBundleShortVersionString</key><string>${VER}</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>BedrockOnLinux</string>
  <key>CFBundleIconFile</key><string>icon</string>
  <key>LSMinimumSystemVersion</key><string>13.0</string>
  <key>NSHighResolutionCapable</key><true/>
  <!-- The launcher window is the application; it never runs as an agent. -->
  <key>LSUIElement</key><false/>
</dict>
</plist>
PLIST

if [[ -n "${CODESIGN_IDENTITY:-}" ]]; then
  codesign --force --deep --options runtime --timestamp \
    --sign "$CODESIGN_IDENTITY" "$APP"
  codesign --verify --strict --verbose=2 "$APP"
fi

ZIP="$OUT/BedrockOnLinux-${VER}-macos.zip"
rm -f "$ZIP"
# ditto, not zip(1): it is the one that preserves the resource forks and the
# signature a bundle needs to survive being unpacked on another Mac.
ditto -c -k --sequesterRsrc --keepParent "$APP" "$ZIP"

echo "Built $APP"
echo "Built $ZIP"
